### ISSUE TITLE
Unable to checkout on windows due to invalid characters in some file names

### ISSUE THREAD

**Issue by Rob-McKay** [embeddedartistry/libc#190]
## Context

On Windows (10) when the command `git clone --recursive git@github.com:embeddedartistry/libc.git` fails with the following error:
```
error: invalid path 'docs/project-history/2020/2020-05/2020-05-07T21:11:03Z_note_AmNIQO0ZxVGx99Li.md'
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. From a windows cmd prompt execute the command `git clone --recursive git@github.com:embeddedartistry/libc.git`

```
Cloning into 'libc'...
remote: Enumerating objects: 4594, done.
remote: Counting objects: 100% (1414/1414), done.
remote: Compressing objects: 100% (821/821), done.
remote: Total 4594 (delta 559), reused 1374 (delta 548), pack-reused 3180
Receiving objects: 100% (4594/4594), 1.63 MiB | 1.84 MiB/s, done.
Resolving deltas: 100% (2632/2632), done.
error: invalid path 'docs/project-history/2020/2020-05/2020-05-07T21:11:03Z_note_AmNIQO0ZxVGx99Li.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by phillipjohnston** [comment]
I'll work on renaming, though I also need to update the pottery tool to not generate files with colons. 

But in general, I recommend cloning with WSL2, I haven't done any work to support native Windows.

**Comment by phillipjohnston** [comment]
lol, looks like I filed an issue for this 3 years ago and then promptly forgot, guess I just need to do it on my own fork :)

https://github.com/npryce/pottery/issues/6

**Comment by Photosounder** [comment]
This issue, the content and utter lack of importance of the two files concerned, the absolute ease with which anyone could have fixed this issue, the fact that this has been getting the way of Windows users cloning this repo for 4 years, the fact that the problem was known all along and brought back to the forefront a few months ago, all of this put together blows my mind. Please don't misunderstand, I don't even mean this in a rude way, I mean this truly makes me feel something hard to describe, this is beautiful, it's an achievement, a touch of surreal in our overly reasonable lives, a delightful yet unintended prank, a rainbow of emotions. 🥹 Thank you for this experience.

**Comment by Photosounder** [comment]
B-but I did! https://github.com/Photosounder/libc
Though I admit it wasn't that easy...

**Comment by phillipjohnston** [comment]
If deleting works, presumably a rename works, and I'll just fix the upstream problem later. I pushed a change to do that. But I don't have a Windows machine, so you can reopen if it's not actually a solution.

**Comment by Photosounder** [comment]
I can't tell if you're joking anymore. Assuming you're not, although it's hard to see why you wouldn't be, my "fix" was so that _I_ could check out the repo and its dependencies, and it was done by crudely deleting the offending folder (not much else I could do from the website), whereas you presumably would want to rename the files. I wouldn't delete your files for you.
